#!/bin/sh
# First you will need to install jshint (npm install jshint -g)
# Enable this pre-commit hook by executing the following from the project root directory
# $ ln -s $PWD/scripts/pre-commit .git/hooks/pre-commit
jshint modules/*.js --config .jshintrc
